version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt -t .
  build:
    commands:
      - aws cloudformation package --template-file template.yml --output-template-file template-out.yml --s3-bucket simplilearn-serverless-project --region us-east-1

artifacts:
  files:
    - template.yml
    - template-out.yml

